name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "your_github_email>"
        git config --global user.name "your_github_username>"
        git remote set-url origin https://7fc935a43975124b08156fcb2c90fffaa515cc3c@github.com/Vieli-Tech/webSiteVieli.git
        npm run deploy

